build:
  image: golang:1.5.1
  environment:
    - GO15VENDOREXPERIMENT=1
  environment:
    - GOPATH=/botd
  commands:
    - make deps
    - make test

publish:
  idocker:
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    username: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: ipedrazas/botd
    tag: $$CI_BUILD_NUMBER
    when:
      branch: master

plugin:
  name: idocker
  desc: Build and Publish images to a Docker registry.
  type: publish
  image: ipedrazas/drone-docker
  labels:
    - idocker
    - image
    - container
