debug: true

build:
  image: golang:1.5.1
  environment:
    - GO15VENDOREXPERIMENT=1
  environment:
    - GOPATH=/botd
  commands:
    - make deps
    - make test
    - make build

notify:
  webhook:
    image: ipedrazas/drone-webhook
    urls:
      - http://deep-api.ipedrazas.k8s.co.uk:5000/webhooks
      - http://deep-api.ipedrazas.k8s.co.uk:5000/debug

publish:
  docker:
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: ipedrazas/botd
    tag:
      - latest
      - "$$BUILD_NUMBER"
    when:
      branch: master

    branch: master

deploy:
  kubernetes:
    image: ipedrazas/drone-kubernetes
    replicationcontrollers: ["deploy/kubernetes/rc.json"]
    services: []
    token: $$TOKEN
    apiserver: $$APISERVER
    namespace: default
    webhook: http://deep-api.ipedrazas.k8s.co.uk:5000/deploy

