build:
  image: golang:1.5.1
  environment:
    - GO15VENDOREXPERIMENT=1
  environment:
    - GOPATH=/botd
  commands:
    - make deps
    - make test

plugin:
  name: Docker
  desc: Build and Publish images to a Docker registry.
  type: publish
  image: ipedrazas/dind
  labels:
    - docker
    - image
    - container
