build:
  image: golang:1.5.1
  environment:
    - GO15VENDOREXPERIMENT=1
  environment:
    - GOPATH=/botd
  commands:
    - make deps
    - make test
publish:
  docker:
    username: ipedrazas
    password: $$DOCKER_PASSWORD
    repo: ipedrazas/botd
    tag: latest
    file: Dockerfile
