build:
  image: golang:1.5.1
  environment:
    - GO15VENDOREXPERIMENT=1
  environment:
    - GOPATH=/botd
  commands:
    - make deps
    - make test

publish:
  docker:
    username: ipedrazas
    password: pa55word
    email: ipedrazas@gmail.com
    repo: ipedrazas/botd2
    tag: latest
    file: Dockerfile
