apiVersion: v1
kind: ReplicationController
metadata:
  name: botd
  labels:
    name: botd
spec:
  replicas: 1
  selector:
    name: botd
  template:
    metadata:
      labels:
        name: botd
    spec:
      containers:
      - name: botd
        image: ipedrazas/botd
        ports:
        - containerPort: 9090
